### ISSUE TITLE
`FileNotFoundError` in `GameMonitor` loop

### ISSUE THREAD

**Issue by kegsmr** [kegsmr/sc4mp-client#110]
```
[91m [12:28:38] [SC4MP/GmThread] (GameMonitor) [ERROR] An unexpected error occurred in the game monitor loop.

Traceback (most recent call last):
  File "sc4mpclient.py", line 3116, in run
  File "sc4mpclient.py", line 3292, in get_cities
  File "core\util.py", line 20, in md5
  File "pathlib.py", line 1222, in open
  File "pathlib.py", line 1078, in _opener
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Kegan\\Documents\\SimCity 4\\_SC4MP\\Regions\\MEGAREGION\\(044-048) - Riverbend - Keg.sc4'
```

**Comment by kegsmr** [comment]
I think this happens because the game renames savegames to match the format `City - {city_name}` when saving. Could be fixed with a new saving implementaiton.
