### ISSUE TITLE
`AttributeError`: 'Server' object has no attribute 'regions'

### ISSUE THREAD

**Issue by kegsmr** [kegsmr/sc4mp-client#111]
```
 [19:30:31] [SC4MP/SldThread] (ServerLoader) [ERROR] An unexpected error occurred in the server loader thread.

'Server' object has no attribute 'regions'

Traceback (most recent call last):
  File "d:/Users/Kegan/Desktop/Projects/mod/sc4/SC4MP/sc4mp-client/sc4mpclient.py", line 2236, in run
    game_monitor = GameMonitor(self.server)
  File "d:/Users/Kegan/Desktop/Projects/mod/sc4/SC4MP/sc4mp-client/sc4mpclient.py", line 2895, in __init__
    self.city_paths, self.city_hashcodes = self.get_cities()
  File "d:/Users/Kegan/Desktop/Projects/mod/sc4/SC4MP/sc4mp-client/sc4mpclient.py", line 3192, in get_cities
    for region in self.server.regions:
AttributeError: 'Server' object has no attribute 'regions'
```

**Comment by kegsmr** [comment]
No idea what's going on here.

**Comment by kegsmr** [comment]
Going to redo the whole game monitor system soon anyway, and I have no way to replicate this error so I'm just going to close this ticket.
