### ISSUE TITLE
"timed out" error during save push

### ISSUE THREAD

**Issue by kegsmr** [kegsmr/sc4mp-client#14]
The client appears to timeout while waiting for a response to a save push from the server. 

Client:
```
[90m [13:33:54] [SC4MP/Thread-22] (GameMonitor) [INFO] Saving...
[90m [13:34:00] [SC4MP/Thread-22] (GameMonitor) [INFO] Saving...
[90m [13:34:00] [SC4MP/Thread-22] (GameMonitor) [INFO] Connecting...
[90m [13:34:00] [SC4MP/Thread-22] (GameMonitor) [INFO] Connected.
[90m [13:34:00] [SC4MP/Thread-22] (GameMonitor) [INFO] Sending file "C:\users\andre\Documents\SimCity 4\_SC4MP\Regions\Zephire\11_8.sc4"...
[90m [13:34:00] [SC4MP/Thread-22] (GameMonitor) [INFO] Sending file "C:\users\andre\Documents\SimCity 4\_SC4MP\Regions\Zephire\City - Conimbriga.sc4"...
[90m [13:34:00] [SC4MP/Thread-22] (GameMonitor) [INFO] Sending file "C:\users\andre\Documents\SimCity 4\_SC4MP\Regions\Zephire\City - Nova Cidade (11).sc4"...
[90m [13:34:00] [SC4MP/Thread-22] (GameMonitor) [INFO] Sending file "C:\users\andre\Documents\SimCity 4\_SC4MP\Regions\Zephire\City - Nova Cidade (13).sc4"...
[90m [13:34:01] [SC4MP/Thread-22] (GameMonitor) [INFO] Sending file "C:\users\andre\Documents\SimCity 4\_SC4MP\Regions\Zephire\City - Nova Cidade (21).sc4"...
[90m [13:34:01] [SC4MP/Thread-22] (GameMonitor) [INFO] Sending file "C:\users\andre\Documents\SimCity 4\_SC4MP\Regions\Zephire\City - Nova Cidade (23).sc4"...
[91m [13:34:11] [SC4MP/Thread-22] (GameMonitor) [ERROR] timed out

Traceback (most recent call last):
  File "sc4mpclient.py", line 2461, in run
  File "sc4mpclient.py", line 2695, in push_save
socket.timeout: timed out

[93m [13:34:11] [SC4MP/Thread-22] (GameMonitor) [WARNING] Save push failed! Unexpected client-side error.
```

Server:
```
[16:04:18] [SC4MP/Main] (Server) [INFO] Connection accepted with 192.168.1.178:42260.
[16:04:18] [SC4MP/Thread-76] (RequestHandler) [INFO] Request: save
[16:04:18] [SC4MP/Thread-76] (RequestHandler) [INFO] Receiving 614611 bytes...
[16:04:18] [SC4MP/Thread-76] (RequestHandler) [INFO] writing to _SC4MP/_Temp/inbound/20230909160418_fb9b854aa8fd963f938cd26ab717440b/Zephire/0.sc4
[16:04:18] [SC4MP/Thread-76] (RequestHandler) [INFO] Receiving 155015 bytes...
[16:04:18] [SC4MP/Thread-76] (RequestHandler) [INFO] writing to _SC4MP/_Temp/inbound/20230909160418_fb9b854aa8fd963f938cd26ab717440b/Zephire/1.sc4
[16:04:18] [SC4MP/Thread-76] (RequestHandler) [INFO] Receiving 158956 bytes...
[16:04:18] [SC4MP/Thread-76] (RequestHandler) [INFO] writing to _SC4MP/_Temp/inbound/20230909160418_fb9b854aa8fd963f938cd26ab717440b/Zephire/2.sc4
[16:04:18] [SC4MP/Thread-76] (RequestHandler) [INFO] Receiving 1962017 bytes...
[16:04:18] [SC4MP/Thread-76] (RequestHandler) [INFO] writing to _SC4MP/_Temp/inbound/20230909160418_fb9b854aa8fd963f938cd26ab717440b/Zephire/3.sc4
[16:04:18] [SC4MP/Thread-76] (RequestHandler) [INFO] Savegame filter 1
[16:04:18] [SC4MP/Thread-76] (RequestHandler) [INFO] NO (13, 7)
[16:04:18] [SC4MP/Thread-76] (RequestHandler) [INFO] YES (11, 8)
[16:04:18] [SC4MP/Thread-76] (RequestHandler) [INFO] YES (10, 8)
[16:04:18] [SC4MP/Thread-76] (RequestHandler) [INFO] NO (9, 9)
[16:04:18] [SC4MP/Thread-76] (RequestHandler) [INFO] Savegame filter 2
[16:04:18] [SC4MP/Thread-76] (RequestHandler) [INFO] YES (11, 8)
[16:04:18] [SC4MP/Thread-76] (RequestHandler) [INFO] NO (10, 8)
[16:04:18] [SC4MP/Thread-4] (RegionsManager) [INFO] Processing task "20230909160418_fb9b854aa8fd963f938cd26ab717440b"...
[16:04:18] [SC4MP/Thread-4] (RegionsManager) [INFO] - done.
```

**Comment by kegsmr** [comment]
Note: this only seems to occur when the server is hosted on Docker

**Comment by kegsmr** [comment]
Note: this occurs on Linux in general.
